imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
          default:
            driver:   "%database_driver%"
            host:     "%database_host%"
            port:     "%database_port%"
            dbname:   "%database_name%"
            user:     "%database_user%"
            password: "%database_password%"
            charset:  UTF8

    orm:
        default_entity_manager:   default
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
              connection: default
              auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    port:      %mailer_port%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


sensio_framework_extra:
    view:
        annotations: false

fos_rest:
    serializer:
        serialize_null: true
    view:
        formats:
            json: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: php
        view_response_listener: force
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    param_fetcher_listener: true
    format_listener:
        default_priorities: ['json']
        prefer_extension: false
        fallback_format: json
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
