# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    countries.countries_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: 'doctrine.orm.default_entity_manager'
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Country

    countries.importer:
        class: AppBundle\Model\RestCountriesImporter
        arguments: ["@doctrine.orm.entity_manager", "@countries.fetcher", "@countries.countries_repository"]

    countries.fetcher:
        class: AppBundle\Model\RestCountriesFetcher
        arguments: ['https://restcountries.eu/rest/v1/all']
